<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
	<AssemblyName>NationalInstruments.TestStand.BlazorOI.WebServer</AssemblyName>
	<RootNamespace>NationalInstruments.TestStand.BlazorOI.WebServer</RootNamespace>
  </PropertyGroup>
  <PropertyGroup>
	<Product>TestStand BlazorUI</Product>
	<ProductName>TestStand Blazor UI</ProductName>
	<Company>National Instruments</Company>
	<Copyright>Copyright (c) National Instruments Corporation. All Rights Reserved.</Copyright>
	<AssemblyTitle>TestStand Blazor User Interface</AssemblyTitle>
	<Description>TestStand Blazor User Interface</Description>
  </PropertyGroup>
  <ItemGroup>
	<PackageReference Include="NimbleBlazor" />
	<PackageReference Include="Serilog.AspNetCore" />
	<PackageReference Include="Serilog.Sinks.Async" />
  </ItemGroup>
  <ItemGroup>
	<ProjectReference Include="..\Controls\Controls.csproj" />
	<ProjectReference Include="..\BlazorOIUtilities\BlazorOIUtilities.csproj" />
  </ItemGroup>
  <ItemGroup>
	<Folder Include="wwwroot\icons\SequencesIcons\" />
  </ItemGroup>
</Project>
