<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
	<AssemblyName>NationalInstruments.TestStand.WebOI.WebServer</AssemblyName>
	<RootNamespace>NationalInstruments.TestStand.WebOI.WebServer</RootNamespace>
  </PropertyGroup>
  <PropertyGroup>
	<Product>TestStand WebOI</Product>
	<ProductName>TestStand Web OI</ProductName>
	<Company>National Instruments</Company>
	<Copyright>Copyright (c) National Instruments Corporation. All Rights Reserved.</Copyright>
	<AssemblyTitle>TestStand Web Operator Interface</AssemblyTitle>
	<Description>TestStand Web Operator Interface</Description>
  </PropertyGroup>
  <ItemGroup>
	<PackageReference Include="NimbleBlazor" />
	<PackageReference Include="Serilog.AspNetCore" />
	<PackageReference Include="Serilog.Sinks.Async" />
  </ItemGroup>
  <ItemGroup>
	<ProjectReference Include="..\Controls\Controls.csproj" />
	<ProjectReference Include="..\WebOIUtilities\WebOIUtilities.csproj" />
  </ItemGroup>
  <ItemGroup>
	<Folder Include="wwwroot\icons\SequencesIcons\" />
  </ItemGroup>
</Project>
