<Project Sdk="Microsoft.NET.Sdk.Razor">
	<PropertyGroup>
		<RootNamespace>NationalInstruments.TestStand.BlazorOI.UI</RootNamespace>
		<AssemblyName>NationalInstruments.TestStand.BlazorUI</AssemblyName>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" />
		<PackageReference Include="Google.Protobuf" />
		<PackageReference Include="Grpc.Net.Client" />
		<PackageReference Include="Grpc.Tools">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="NimbleBlazor" />
		<PackageReference Include="TestableIO.System.IO.Abstractions.Wrappers" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\SharedDomain\SharedDomain.csproj" />
		<ProjectReference Include="..\BlazorOIUtilities\BlazorOIUtilities.csproj" />
	</ItemGroup>
	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>
</Project>
